
USE lovesync;

CREATE TABLE usuarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  mail VARCHAR(255) NOT NULL UNIQUE,
  passwd VARCHAR(255) NOT NULL,
  fechaNacimiento DATE NOT NULL,
  fechaCreacionCuenta TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE perfil (
  id INT AUTO_INCREMENT PRIMARY KEY,  
  user_id INT NOT NULL,
  genero ENUM('hombre','mujer','otro') NOT NULL,
  genint ENUM('hombre','mujer','todos') NOT NULL,
  bio VARCHAR(500),
  intereses JSON,
  ubicacion VARCHAR(100) NOT NULL,
  LenguajeDelAmor VARCHAR(50) NOT NULL,
  edad INT, -- Nueva columna basada en tus datos

  CONSTRAINT fk_perfil_usuarios
    FOREIGN KEY (user_id)
    REFERENCES usuarios(id)
    ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE matches (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id_1 INT NOT NULL,
  user_id_2 INT NOT NULL,
  estado ENUM('pendiente','aceptado','rechazado','bloqueado') DEFAULT 'pendiente',
  quien_acepta INT,
  fechaMatch TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  fechaActualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  
  CONSTRAINT fk_matches_user1
    FOREIGN KEY (user_id_1)
    REFERENCES usuarios(id)
    ON DELETE CASCADE,
  
  CONSTRAINT fk_matches_user2
    FOREIGN KEY (user_id_2)
    REFERENCES usuarios(id)
    ON DELETE CASCADE,

  CONSTRAINT fk_matches_quien_acepta
    FOREIGN KEY (quien_acepta)
    REFERENCES usuarios(id)
    ON DELETE SET NULL,
  
  CONSTRAINT ck_usuarios_diferentes
    CHECK (user_id_1 < user_id_2),
  
  UNIQUE KEY unique_match (user_id_1, user_id_2)
) ENGINE=InnoDB;


INSERT INTO usuarios (nombre, mail, passwd, fechaNacimiento) VALUES
('Alba Rodríguez', 'alba.rodriguez@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '1999-10-27'),
('Marina López', 'marinalopez@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '1996-09-08'),
('Carla Romero', 'carla.romero@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '2003-09-15'),
('Emma Müller', 'emma.muller@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '2001-08-15'),
('Martina García', 'martina.garcia@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '1998-05-15'),
('Andrea Martín', 'andrea.martin@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '2001-08-15'),
('Sara Sánchez', 'sara.sanchez@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '1996-03-22'),
('Paula Ruiz', 'paula.ruiz@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '2004-12-05'),
('Carmen Torres', 'carmen.torres@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '1998-05-20'),
('Clara Jiménez', 'clara.jimenez@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '2003-05-18'),
('Irene Vargas', 'irene.vargas.goals@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '1995-07-15'),
('Sofía Gil', 'sofia.gil@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '2006-03-20'),
('Laura Navarro', 'laura.navarro@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '1999-07-15'),
('Elena Vidal', 'elena.vidal@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '1998-07-10'),
('Rocío Aguilar', 'rocio.rocker@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '1996-03-24'),
('Laia Font', 'laia.font.cultura@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '1996-05-20'),
('Vega Morales', 'vega.morales@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '2001-05-10'),
('Lola Ibáñez', 'lola.ibanez@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '2002-05-10'),
('Nerea Castro', 'nerea.castro@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '1998-07-25'),
('Cayetana Cruz', 'cayetana.cruz@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '1999-07-10'),
('Silvia Méndez', 'silvia.kawaii@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '2005-07-25'),
('Belén Ortiz', 'belen.ortiz.travel@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '1997-01-01'),
('Diana Cano', 'diana.cano@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '2001-04-18'),
('Victoria Sanz', 'victoria.sanz@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '2003-09-01'),
('Natalia Flores', 'natalia.flores@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '1999-06-15'),
('Julia Ruiz', 'julia.ruiz@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '1995-11-20'),
('Mónica Soler', 'monica.soler@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '2002-05-10'),
('Estela Ríos', 'estela.rios@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '1999-07-28'),
('Cris León', 'cris.leon@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '2003-05-20'),
('Beatriz Gil', 'beatriz.foodie@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '1997-06-15'),
('Ainhoa Puig', 'ainhoa.puig@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '2001-07-28'),
('Rosa Méndez', 'rosa.mendez.bio@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '1996-04-10'),
('Elsa Pires', 'elsa.pires@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '1999-11-20'),
('Miriam Costa', 'miriam.costa@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '1998-06-25'),
('Patri Serrano', 'patri.serrano@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '2003-05-15'),
('Celia Rivas', 'celia.rivas@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '1999-01-20'),
('Noa Valero', 'usuario.generico@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '2002-05-18'),
('Lidia Marín', 'lidia.marin@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '1995-03-22'),
('Inés Otero', 'ines.otero@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '2004-06-15'),
('Marta G.', 'marta.g@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '1997-03-10'),
('Vero Sanz', 'vero.s@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '2001-08-15'),
('Alicia Pla', 'alicia.pla@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '1998-05-20'),
('Sandra Luque', 'sandra.luque@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '2006-05-19'),
('Tania Ferrer', 'tania.ferrer.box@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '1999-04-18'),
('Mireia Sol', 'mireia.sol@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '2000-08-01'),
('Clàudia BCN', 'claudia.bcn@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '1996-05-15'),
('Raquel M.', 'raquel.metal@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '2002-05-20'),
('Eva Garrido', 'eva.garrido@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '1997-01-20'),
('Nuria Gil', 'nuria.gil@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '2003-05-10'),
('Paula', 'paula.pau@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '2003-05-20'),
('Lara Torres', 'lara.torres@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '1999-05-15'),
('Aida Gómez', 'aida.gomez@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '1995-03-10'),
('Carla', 'carla.charlie@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '2003-09-08'),
('Berta Solís', 'berta.solis@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '1998-08-05'),
('Gal·la Martí', 'galla.marti@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '1999-07-28'),
('Iris Vega', 'iris.vega@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '2002-05-20'),
('Sonia Pires', 'sonia.pires@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '1996-06-15'),
('Noemí', 'noe.fiesta@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '2004-09-18'),
('Elsa Durán', 'elsa.duran@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '2001-09-01'),
('Marina Gil', 'marina.gil.fit@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '1997-03-10'),
('Patri León', 'patri.leon@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '2005-08-15'),
('Eva', 'eva.vivi@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '1999-06-15'),
('Nuria Sanz', 'nuria.sanz@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '1999-11-20'),
('Celia Roda', 'celia.roda@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '1995-12-15'),
('Alba', 'alba.babi@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '2003-05-25'),
('Raquel F.', 'raquel.f@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '1998-05-15'),
('Sandra M.', 'sandra.m@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '2002-05-10'),
('Paula Art', 'paula.pau.art@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '1996-03-20'),
('Irene V.', 'irene.v.erasmus@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '2000-05-15'),
('Lucía', 'lucia.lu@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '2004-04-10'),
('Marta Soler', 'marta.soler@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '1998-05-15'),
('Cris', 'cris.kika.motos@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '2001-04-10'),
('Bea Ortiz', 'bea.ortiz.yoga@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '1997-06-15'),
('Andrea P.', 'andrea.p@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '2006-05-18'),
('Tania Gil', 'tania.gil@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '1995-07-15'),
('Carmen R.', 'carmen.r.violin@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '2003-08-15'),
('Laura', 'laura.lau@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '1998-05-15'),
('Elena M.', 'elena.m@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '1999-06-25'),
('Sara', 'sara.sari@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '2002-05-18'),
('Nerea F.', 'nerea.f@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '1996-06-15'),
('Rocío V.', 'rocio.vargas@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '2004-05-15'),
('Clara', 'clara.bici@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '1999-01-20'),
('Inés G.', 'ines.g@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '1997-06-25'),
('Silvia T.', 'silvia.t@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '2001-04-12'),
('Miriam L.', 'miriam.l@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '1994-08-16'),
('Julia', 'julia.juls@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '2003-05-20'),
('Natalia R.', 'natalia.reposteria@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '1998-05-12'),
('Estefanía M.', 'estefania.m@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '1999-07-16'),
('Ainhoa S.', 'ainhoa.s@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '2002-05-18'),
('Belén', 'belen.montana@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '1996-06-15'),
('Mónica P.', 'monica.gamer@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '2003-08-10'),
('Laura G.', 'laura.g@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '1998-03-10'),
('Diana F.', 'diana.f@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '1996-05-15'),
('Vero', 'vero.v@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '2001-08-15'),
('Olga M.', 'olga.m.chill@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '1995-03-01'),
('Celia', 'celia.ce@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '2003-11-20'),
('Raquel B.', 'raquel.b@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '1997-12-15'),
('Marta', 'marta.tita@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '2006-05-15'),
('Abril', 'abril.lectora@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '2000-05-18'),
('Zoe', 'zoe.todocuriosa@google.com', '$2b$10$V66poPwxknzYwkIi.ev5E.zd/hWmCvzfJeAcCi3Lz.UiyE8qA2Rna', '1999-07-28');

INSERT INTO perfil (user_id, genero, genint, bio, intereses, ubicacion, LenguajeDelAmor, edad) VALUES
(2, 'mujer', 'todos', 'Intentando ser arquitecta y no morir en el intento. Paso mi vida entre planos y cafeterías de especialidad.', JSON_ARRAY('Arquitectura', 'Museos', 'Café'), 'No especificada', 'Actos de servicio', 27),
(3, 'mujer', 'todos', 'Mido 1,56 :( pero tengo carácter de sobra. Me encontrarás en el skatepark o buscando el próximo concierto.', JSON_ARRAY('Skate', 'Punk', 'Tatuajes'), 'No especificada', 'Contacto físico', 20),
(4, 'mujer', 'todos', 'It helps if u speak Spanish (extrangera). Learning the language and loving the culture.', JSON_ARRAY('Idiomas', 'Viajes', 'Tapas'), 'No especificada', 'Palabras de afirmación', 23),
(5, 'mujer', 'todos', 'No es ser superficial, es tener estándares. Me gusta cuidarme y los sitios bonitos.', JSON_ARRAY('Moda', 'Instagram', 'Pilates'), 'No especificada', 'Recibir regalos', 26),
(6, 'mujer', 'todos', 'Si no te mola el humor negro no me conozcas. Me fascinan las cosas raras y los anillos con calaveras.', JSON_ARRAY('Humor negro', 'Ocultismo'), 'No especificada', 'Palabras de afirmación', 22),
(7, 'mujer', 'todos', 'Personas directas y planes improvisados. La ciudad me agobia, prefiero dormir en mi furgoneta.', JSON_ARRAY('Senderismo', 'Camping', 'Furgo'), 'No especificada', 'Tiempo de calidad', 28),
(8, 'mujer', 'todos', 'Idk why im here. Looking for friends maybe. Me encanta el perreo y arreglarme para salir.', JSON_ARRAY('TikTok', 'Reggaetón', 'Uñas'), 'No especificada', 'Contacto físico', 19),
(9, 'mujer', 'todos', 'Un alma vieja. Disfruto conocer cosas nuevas, sobre todo si son libros o bares de jazz.', JSON_ARRAY('Poesía', 'Jazz', 'Vino tinto'), 'No especificada', 'Palabras de afirmación', 25),
(10, 'mujer', 'todos', 'Im not perfect but im kind. Intento dejar el mundo mejor de lo que lo encontré.', JSON_ARRAY('Voluntariado', 'Yoga', 'Vegano'), 'No especificada', 'Actos de servicio', 21),
(11, 'mujer', 'todos', 'Directa y ambiciosa. Tengo mis metas claras. Busco a alguien que esté a mi nivel.', JSON_ARRAY('Negocios', 'Crossfit', 'Metas'), 'No especificada', 'Recibir regalos', 29),
(12, 'mujer', 'todos', 'Solo estoy curiosa sobre esta aplicación :) Acabo de empezar la uni. Soy bastante payasa.', JSON_ARRAY('Universidad', 'Salir', 'Amigas'), 'No especificada', 'Palabras de afirmación', 18),
(13, 'mujer', 'todos', 'La música es mi vida. ¿Anillos y medallones? Sí, y ropa de segunda mano.', JSON_ARRAY('Indie', 'Vinilos', 'Vintage'), 'No especificada', 'Tiempo de calidad', 24),
(14, 'mujer', 'todos', 'Fan de juego de tronos y bastante graciosa. No soy una princesa, soy más tipo Arya.', JSON_ARRAY('Fantasía', 'GOT', 'Rol'), 'No especificada', 'Tiempo de calidad', 25),
(15, 'mujer', 'todos', 'Uno que no sea princesa, que para princesas ya estoy yo. Me gustan las motos y la birra.', JSON_ARRAY('Motos', 'Rock', 'Cerveza'), 'No especificada', 'Actos de servicio', 27),
(16, 'mujer', 'todos', 'Buscando lo que sea y mejor si es en català. Me encanta fer vermut los domingos.', JSON_ARRAY('Cultura', 'Vermut', 'Teatro'), 'No especificada', 'Tiempo de calidad', 28),
(17, 'mujer', 'todos', 'Donde pueda ser yo. Creo en las energías y el destino. Segunda oportunidad a lovesync!', JSON_ARRAY('Tarot', 'Cristales', 'Boho'), 'No especificada', 'Contacto físico', 23),
(18, 'mujer', 'todos', 'Holaaaaaaa. No sé qué escribir. Básicamente soy un caos gracioso. Me río de todo.', JSON_ARRAY('Memes', 'Pizza', 'Comedia'), 'No especificada', 'Contacto físico', 22),
(19, 'mujer', 'todos', 'Listo y gracioso, con un lado friki. Si no entiendes mi sarcasmo, lo llevamos mal.', JSON_ARRAY('Stand-up', 'Guiones', 'Series'), 'No especificada', 'Palabras de afirmación', 26),
(20, 'mujer', 'todos', 'Me gustan las cosas bien hechas. Viajes, fiesta (pero en reservados) y buena compañía.', JSON_ARRAY('Hípica', 'Vela', 'Esquí'), 'No especificada', 'Recibir regalos', 24),
(21, 'mujer', 'todos', 'Mido 1,50 solo. Me encantan las cosas cuquis y el color rosa. Busco a alguien que me trate con dulzura.', JSON_ARRAY('K-pop', 'Kawaii', 'Dulces'), 'No especificada', 'Recibir regalos', 19),
(22, 'mujer', 'todos', 'Tengo la maleta siempre lista. Busco compañero de aventuras que no se queje por caminar.', JSON_ARRAY('Mochilera', 'Mapas', 'Asia'), 'No especificada', 'Tiempo de calidad', 26),
(23, 'mujer', 'todos', 'Tengo un lado friki. Paso mucho tiempo en el PC. Busco mi duo carry. No soy de discotecas.', JSON_ARRAY('Gaming', 'PC', 'Twitch'), 'No especificada', 'Actos de servicio', 23),
(24, 'mujer', 'todos', 'Personas directas y planes improvisados. Si me dices playa, ya estoy en el coche.', JSON_ARRAY('Roadtrips', 'Festivales', 'Mar'), 'No especificada', 'Tiempo de calidad', 21),
(25, 'mujer', 'todos', 'Solo busco conocer gente nueva :) y repartir buena vibra. Soy la amiga que siempre sonríe.', JSON_ARRAY('Girasoles', 'Perros', 'Yoga'), 'No especificada', 'Palabras de afirmación', 24),
(26, 'mujer', 'todos', 'Disfruto conocer cosas nuevas a través de mi cámara. Busco un muso o alguien que aprecie el silencio.', JSON_ARRAY('Fotografía', 'Arte', 'Vino'), 'No especificada', 'Tiempo de calidad', 29),
(27, 'mujer', 'todos', 'Vayamos al grano: vivo en chanclas. Si no te gusta la arena y el salitre, difícil.', JSON_ARRAY('Surf', 'Playa', 'Furgoneta'), 'No especificada', 'Contacto físico', 22),
(28, 'mujer', 'todos', 'Donde pueda ser yo <3. Mi habitación es un caos de pinceles y ropa. Busco una mente creativa.', JSON_ARRAY('Pintura', 'Danza', 'Caos'), 'No especificada', 'Contacto físico', 25),
(29, 'mujer', 'todos', 'Patinar (amateur) y música urbana. Soy leal y directa. Busco un chico con estilo.', JSON_ARRAY('Trap', 'Gorras', 'Zapas'), 'No especificada', 'Tiempo de calidad', 20),
(30, 'mujer', 'todos', 'Me encanta comer bien. Busco un foodie que disfrute tanto de un Michelin como de unas bravas.', JSON_ARRAY('Gastronomía', 'Michelin', 'Viajes'), 'No especificada', 'Actos de servicio', 27),
(31, 'mujer', 'todos', 'Frikis bienvenidas. Fan de los mundos de fantasía. Si me llevas al Salón del Manga, me enamoro.', JSON_ARRAY('Anime', 'Cosplay', 'Manga'), 'No especificada', 'Tiempo de calidad', 23),
(32, 'mujer', 'todos', 'Busco vida tranquila. Si eres urbanita estresado, no encajamos. Me gustan las plantas.', JSON_ARRAY('Jardinería', 'Campo', 'Bio'), 'No especificada', 'Actos de servicio', 28),
(33, 'mujer', 'todos', 'La noche es mía. Me gusta la música electrónica oscura y la estética industrial.', JSON_ARRAY('Techno', 'Rave', 'Negro'), 'No especificada', 'Contacto físico', 24),
(34, 'mujer', 'todos', 'Obsesionada con los documentales de crímenes. Humor negro necesario.', JSON_ARRAY('True Crime', 'Misterio', 'Gatos'), 'No especificada', 'Tiempo de calidad', 26),
(35, 'mujer', 'todos', 'Mido 1,56 pero levanto más peso que tú. El gym es mi terapia.', JSON_ARRAY('Gym', 'Fitness', 'Salud'), 'No especificada', 'Contacto físico', 21),
(36, 'mujer', 'todos', 'Muy Escorpio. Si no crees en esto, no pasa nada, pero respétalo. Intensidad emocional.', JSON_ARRAY('Astrología', 'Horóscopo'), 'No especificada', 'Palabras de afirmación', 25),
(37, 'mujer', 'todos', 'Me gustan los chicos con flequillo y que toquen el bajo. Soy de ir a conciertos pequeños.', JSON_ARRAY('Indie-Pop', 'Conciertos', 'Bares'), 'No especificada', 'Tiempo de calidad', 22),
(38, 'mujer', 'todos', 'Intentando ser arquitecta. Me gusta el orden y el diseño nórdico. Busco estabilidad.', JSON_ARRAY('Arquitectura', 'Diseño', 'Orden'), 'No especificada', 'Actos de servicio', 29),
(39, 'mujer', 'todos', 'Vayamos al grano: quiero pasármelo bien. Verano, playa y discoteca.', JSON_ARRAY('Fiesta', 'Playa', 'Amigas'), 'No especificada', 'Contacto físico', 20),
(40, 'mujer', 'todos', 'Introvertida pero interesante. Prefiero un libro a una discoteca. Busco a alguien paciente.', JSON_ARRAY('Lectura', 'Té', 'Lluvia'), 'No especificada', 'Palabras de afirmación', 27),
(41, 'mujer', 'todos', 'Me va la gasolina. Si tienes un coche japonés de los 90, cásate conmigo.', JSON_ARRAY('Motor', 'Coches', 'Drift'), 'No especificada', 'Tiempo de calidad', 23),
(42, 'mujer', 'todos', 'Soy enfermera, tengo mucha paciencia pero poco tiempo libre. Busco aprovecharlo bien.', JSON_ARRAY('Enfermería', 'Cuidar', 'Café'), 'No especificada', 'Actos de servicio', 26),
(43, 'mujer', 'todos', 'Holaaaaaaa. Soy nueva en esto. Me gustan los videojuegos y los peluches.', JSON_ARRAY('Gamer', 'Anime', 'Cosas cuquis'), 'No especificada', 'Recibir regalos', 18),
(44, 'mujer', 'todos', 'No soy delicada. Hago boxeo y me gusta la adrenalina. Busco a alguien con sangre en las venas.', JSON_ARRAY('Boxeo', 'Deporte', 'Retos'), 'No especificada', 'Contacto físico', 25),
(45, 'mujer', 'todos', 'Disfruto conocer cosas nuevas, especialmente ecológicas. Soy vegetariana y amo la montaña.', JSON_ARRAY('Naturaleza', 'Eco', 'Veggie'), 'No especificada', 'Actos de servicio', 24),
(46, 'mujer', 'todos', 'Mejor si es en català. Participo en la cultura popular y me encanta mi tierra.', JSON_ARRAY('Cultura Cat', 'Castellers', 'Vinos'), 'No especificada', 'Tiempo de calidad', 28),
(47, 'mujer', 'todos', 'Anillos y medallones, y mucha tinta. Me gusta el metal y la estética oscura.', JSON_ARRAY('Tatuajes', 'Piercings', 'Metal'), 'No especificada', 'Contacto físico', 22),
(48, 'mujer', 'todos', 'Me gustan los hombres con ambición. Trabajo en finanzas. Busco pareja de poder.', JSON_ARRAY('Finanzas', 'Inversión', 'Lujo'), 'No especificada', 'Recibir regalos', 27),
(49, 'mujer', 'todos', 'Buen rollo ante todo. Patinar, playa y cervecitas. No me complico la vida.', JSON_ARRAY('Surfskate', 'Playa', 'Chill'), 'No especificada', 'Contacto físico', 21),
(50, 'mujer', 'todos', 'Soy profe de infantil, así que tengo paciencia infinita. Busco a alguien familiar.', JSON_ARRAY('Docencia', 'Niños', 'Manualidades'), 'No especificada', 'Palabras de afirmación', 29),
(51, 'mujer', 'todos', 'No busco novio, busco compañero de rave. Si no aguantas hasta el cierre, no me hables.', JSON_ARRAY('Techno', 'Ropa negra', 'Piercings'), 'No especificada', 'Tiempo de calidad', 24),
(52, 'mujer', 'todos', 'Disfruto conocer cosas nuevas, especialmente si se pueden comer. Busco un foodie.', JSON_ARRAY('Gastronomía', 'Vinos', 'Viajes'), 'No especificada', 'Actos de servicio', 29),
(53, 'mujer', 'todos', 'Mido 1,56 :( pero ocupo mucho espacio. Me paso la vida en el skatepark.', JSON_ARRAY('Skate', 'Grafiti', 'Hip Hop'), 'No especificada', 'Contacto físico', 21),
(54, 'mujer', 'todos', 'Intentando ser arquitecta. Busco a alguien que entienda que no tengo tiempo libre.', JSON_ARRAY('Arquitectura', 'Arte', 'Museos'), 'No especificada', 'Palabras de afirmación', 26),
(55, 'mujer', 'todos', 'Amante de la tierra y las excursiones. Si no te gusta Els Pets o Oques Grasses, difícil.', JSON_ARRAY('Indepe', 'Música en català', 'Montaña'), 'No especificada', 'Tiempo de calidad', 25),
(56, 'mujer', 'todos', 'Anillos y medallones? Sí. Soy esa chica witchy. Leo el tarot.', JSON_ARRAY('Brujería', 'Tarot', 'Gatos'), 'No especificada', 'Recibir regalos', 22),
(57, 'mujer', 'todos', 'Si no te mola el humor negro no me conozcas. Me río en los momentos inapropiados.', JSON_ARRAY('Humor negro', 'Cine B', 'Horror'), 'No especificada', 'Palabras de afirmación', 28),
(58, 'mujer', 'todos', 'Holaaaaaaa. Solo busco pasarlo bien. Me encanta bailar hasta abajo.', JSON_ARRAY('Fiesta', 'Reggaetón', 'TikTok'), 'No especificada', 'Contacto físico', 20),
(59, 'mujer', 'todos', 'Fan de la cultura asiática. Busco a mi oppa o alguien para comer ramen.', JSON_ARRAY('K-Pop', 'Dramas coreanos', 'Café'), 'No especificada', 'Recibir regalos', 23),
(60, 'mujer', 'todos', 'Personas directas y deportistas. El sofá no es un plan. Me levanto a las 6 AM para entrenar.', JSON_ARRAY('Crossfit', 'Nutrición', 'Playa'), 'No especificada', 'Contacto físico', 27),
(61, 'mujer', 'todos', 'Idk why im here. Looking for friends maybe. Enséñame los sitios guays.', JSON_ARRAY('Universidad', 'Salir', 'Cotilleos'), 'No especificada', 'Tiempo de calidad', 19),
(62, 'mujer', 'todos', 'Why not? Dejé mi trabajo para viajar en furgo. Busco espíritu libre.', JSON_ARRAY('Furgoneta', 'Surf', 'Naturaleza'), 'No especificada', 'Actos de servicio', 25),
(63, 'mujer', 'todos', 'Im not perfect but im kind (y un poco friki). Paso el finde rankeando en el LoL.', JSON_ARRAY('Videojuegos', 'Twitch', 'Anime'), 'No especificada', 'Tiempo de calidad', 24),
(64, 'mujer', 'todos', 'Me gusta la buena vida. Busco un hombre con metas claras y solvencia.', JSON_ARRAY('Negocios', 'Moda', 'Lujo'), 'No especificada', 'Recibir regalos', 29),
(65, 'mujer', 'todos', 'Me mola el rollo urbano. Si vistes bien y escuchas trap, tienes puntos.', JSON_ARRAY('Trap', 'Streetwear', 'Zapas'), 'No especificada', 'Contacto físico', 21),
(66, 'mujer', 'todos', 'Introvertida. Prefiero quedarme en casa leyendo que salir de fiesta.', JSON_ARRAY('Literatura', 'Poesía', 'Gatos'), 'No especificada', 'Palabras de afirmación', 26),
(67, 'mujer', 'todos', 'Uno que no sea princesa. Me gusta el metal y la cerveza barata. Dura por fuera.', JSON_ARRAY('Tatuajes', 'Metal', 'Cerveza'), 'No especificada', 'Contacto físico', 22),
(68, 'mujer', 'todos', 'A ver si esta vez encuentro a alguien creativo y sensible. Fotografía analógica.', JSON_ARRAY('Fotografía', 'Arte', 'Indie'), 'No especificada', 'Tiempo de calidad', 28),
(69, 'mujer', 'todos', 'It helps if u speak spanish (extrangera). Soy de fuera pero amo España.', JSON_ARRAY('Erasmus', 'Idiomas', 'Fiesta'), 'No especificada', 'Palabras de afirmación', 24),
(70, 'mujer', 'todos', 'Im not perfect but im kind. Rescato animales y como plantas.', JSON_ARRAY('Animales', 'Veganismo', 'Eco'), 'No especificada', 'Actos de servicio', 20),
(71, 'mujer', 'todos', 'Fan de juego de tronos y bastante graciosa. Sé mucho de dragones.', JSON_ARRAY('GoT', 'Fantasía', 'Rol'), 'No especificada', 'Tiempo de calidad', 25),
(72, 'mujer', 'todos', 'Me va la velocidad. Tengo moto propia. Si te dan miedo las chicas rápidas, bye.', JSON_ARRAY('Motos', 'Adrenalina', 'Coches'), 'No especificada', 'Tiempo de calidad', 23),
(73, 'mujer', 'todos', 'Donde pueda ser yo <3. Busco paz mental y conexión espiritual.', JSON_ARRAY('Yoga', 'Meditación', 'Playa'), 'No especificada', 'Contacto físico', 27),
(74, 'mujer', 'todos', 'Solo estoy curiosa sobre esta aplicación :) Quiero ver qué hay por aquí.', JSON_ARRAY('Discoteca', 'Amigas', 'Ligues'), 'No especificada', 'Palabras de afirmación', 18),
(75, 'mujer', 'todos', 'Trabajo mucho, duermo poco. Busco a alguien que me mime cuando salgo de guardia.', JSON_ARRAY('Enfermería', 'Guardias', 'Café'), 'No especificada', 'Actos de servicio', 29),
(76, 'mujer', 'todos', 'Toco el violín. Me gusta la música clásica y la gente educada.', JSON_ARRAY('Música clásica', 'Violín', 'Arte'), 'No especificada', 'Palabras de afirmación', 21),
(77, 'mujer', 'todos', 'Listo y gracioso, con un lado friki. Si nos reímos juntos, ya está hecho.', JSON_ARRAY('Humor', 'Memes', 'Cerveza'), 'No especificada', 'Tiempo de calidad', 26),
(78, 'mujer', 'todos', 'Mi casa parece una selva. Me gustan más las plantas que las personas.', JSON_ARRAY('Plantas', 'Botánica', 'Verde'), 'No especificada', 'Actos de servicio', 24),
(79, 'mujer', 'todos', 'Vayamos al grano: quiero vivir viajando. Espíritu nómada.', JSON_ARRAY('Surf', 'Vanlife', 'Verano'), 'No especificada', 'Tiempo de calidad', 22),
(80, 'mujer', 'todos', 'Intentando ser arquitecta. Me fijo en los detalles y en la estética.', JSON_ARRAY('Arquitectura', 'Diseño', 'Cool'), 'No especificada', 'Recibir regalos', 28),
(81, 'mujer', 'todos', 'Otaku orgullosa. Hago cosplay y voy a eventos. Busco a mi Senpai.', JSON_ARRAY('Anime', 'Cosplay', 'Japón'), 'No especificada', 'Tiempo de calidad', 20),
(82, 'mujer', 'todos', 'Mido 1,56 :( pero subo puertos de montaña. La bici es mi pasión.', JSON_ARRAY('Bicis', 'Ciclismo', 'Ruta'), 'No especificada', 'Actos de servicio', 25),
(83, 'mujer', 'todos', 'Actriz en proceso. Me encanta el drama (en el escenario). Busco alguien intenso.', JSON_ARRAY('Teatro', 'Cultura', 'Vinos'), 'No especificada', 'Palabras de afirmación', 27),
(84, 'mujer', 'todos', 'La noche me confunde. Techno, amigos y amaneceres.', JSON_ARRAY('Fiesta', 'Techno', 'Gafas'), 'No especificada', 'Contacto físico', 23),
(85, 'mujer', 'todos', 'Personas directas. Soy abogada, así que gano todas las discusiones.', JSON_ARRAY('Abogada', 'Leyes', 'Debate'), 'No especificada', 'Palabras de afirmación', 29),
(86, 'mujer', 'todos', 'Me gusta la música en directo y dormir en tienda de campaña. Sin lujos.', JSON_ARRAY('Indie', 'Festivales', 'Camping'), 'No especificada', 'Tiempo de calidad', 21),
(87, 'mujer', 'todos', 'Hago los mejores brownies. Me encanta cocinar para la gente que quiero.', JSON_ARRAY('Cocina', 'Postres', 'Dulce'), 'No especificada', 'Actos de servicio', 26),
(88, 'mujer', 'todos', 'Idk why im here. Quizás para encontrar inspiración. Me encanta la moda.', JSON_ARRAY('Moda', 'Tendencias', 'Blog'), 'No especificada', 'Recibir regalos', 24),
(89, 'mujer', 'todos', 'Anillos y medallones. Estética alternativa. Chicos con tatuajes.', JSON_ARRAY('Tatuajes', 'Piercings', 'Rock'), 'No especificada', 'Contacto físico', 22),
(90, 'mujer', 'todos', 'Prefiero los perros a las personas. Vivo cerca de la montaña.', JSON_ARRAY('Montaña', 'Perros', 'Silencio'), 'No especificada', 'Tiempo de calidad', 28),
(91, 'mujer', 'todos', 'Juego Valorant hasta las tantas. Soy tímida en persona, loca online.', JSON_ARRAY('Gaming', 'Discord', 'Valorant'), 'No especificada', 'Tiempo de calidad', 20),
(92, 'mujer', 'todos', 'Viajo con presupuesto lowcost a donde sea. Busco compañero flexible.', JSON_ARRAY('Viajes', 'Mochila', 'Lowcost'), 'No especificada', 'Tiempo de calidad', 25),
(93, 'mujer', 'todos', 'Analizo todo demasiado. Soy psicóloga. Charlas profundas.', JSON_ARRAY('Psicología', 'Mente', 'Charlas'), 'No especificada', 'Palabras de afirmación', 27),
(94, 'mujer', 'todos', 'Patinar (amateur). Me gusta el arte callejero y la cultura hip hop.', JSON_ARRAY('Skate', 'Arte urbano', 'Rap'), 'No especificada', 'Contacto físico', 23),
(95, 'mujer', 'todos', 'Planes tranquilos. Sofá, vino, queso y buena serie.', JSON_ARRAY('Vino', 'Queso', 'Netflix'), 'No especificada', 'Contacto físico', 29),
(96, 'mujer', 'todos', 'Soy Piscis, así que soy puro drama y emoción. Busco a alguien que me de tierra.', JSON_ARRAY('Astrología', 'Horóscopo', 'Magia'), 'No especificada', 'Palabras de afirmación', 21),
(97, 'mujer', 'todos', 'Im not perfect but im kind. Trabajo en una ONG. Me importa la justicia social.', JSON_ARRAY('Voluntariado', 'Social', 'ONG'), 'No especificada', 'Actos de servicio', 26),
(98, 'mujer', 'todos', 'Holaaaaaaa. Soy un terremoto. Me paso el día grabando Tiktoks.', JSON_ARRAY('Tiktok', 'Bailes', 'Risas'), 'No especificada', 'Contacto físico', 18),
(99, 'mujer', 'todos', 'Mido 1,50 solo, tamaño de bolsillo. Ratón de biblioteca.', JSON_ARRAY('Libros', 'Café', 'Lluvia'), 'No especificada', 'Palabras de afirmación', 24),
(100, 'mujer', 'todos', 'Disfruto conocer cosas nuevas. Un día hago escalada, otro voy a la ópera. Why not?', JSON_ARRAY('Todo', 'Curiosa', 'Vida'), 'No especificada', 'Tiempo de calidad', 25);